# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\serialTool\ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_serialTool(object):
    def setupUi(self, serialTool):
        serialTool.setObjectName("serialTool")
        serialTool.resize(592, 518)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/serialIcon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        serialTool.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(serialTool)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.serialNumComb = QtWidgets.QComboBox(self.groupBox)
        self.serialNumComb.setObjectName("serialNumComb")
        self.verticalLayout.addWidget(self.serialNumComb)
        self.serialBaudComb = QtWidgets.QComboBox(self.groupBox)
        self.serialBaudComb.setObjectName("serialBaudComb")
        self.serialBaudComb.addItem("")
        self.serialBaudComb.addItem("")
        self.serialBaudComb.addItem("")
        self.serialBaudComb.addItem("")
        self.serialBaudComb.addItem("")
        self.serialBaudComb.addItem("")
        self.serialBaudComb.addItem("")
        self.verticalLayout.addWidget(self.serialBaudComb)
        self.serialCheckComb = QtWidgets.QComboBox(self.groupBox)
        self.serialCheckComb.setObjectName("serialCheckComb")
        self.serialCheckComb.addItem("")
        self.verticalLayout.addWidget(self.serialCheckComb)
        self.serialDataLenComb = QtWidgets.QComboBox(self.groupBox)
        self.serialDataLenComb.setObjectName("serialDataLenComb")
        self.serialDataLenComb.addItem("")
        self.serialDataLenComb.addItem("")
        self.serialDataLenComb.addItem("")
        self.serialDataLenComb.addItem("")
        self.verticalLayout.addWidget(self.serialDataLenComb)
        self.serialStopComb = QtWidgets.QComboBox(self.groupBox)
        self.serialStopComb.setObjectName("serialStopComb")
        self.serialStopComb.addItem("")
        self.serialStopComb.addItem("")
        self.verticalLayout.addWidget(self.serialStopComb)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openBtn = QtWidgets.QPushButton(self.groupBox)
        self.openBtn.setObjectName("openBtn")
        self.horizontalLayout.addWidget(self.openBtn)
        self.closeBtn = QtWidgets.QPushButton(self.groupBox)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout.addWidget(self.closeBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.asciiRecvRbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.asciiRecvRbtn.setObjectName("asciiRecvRbtn")
        self.horizontalLayout_2.addWidget(self.asciiRecvRbtn)
        self.hexRecvRbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.hexRecvRbtn.setCheckable(True)
        self.hexRecvRbtn.setChecked(True)
        self.hexRecvRbtn.setObjectName("hexRecvRbtn")
        self.horizontalLayout_2.addWidget(self.hexRecvRbtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.autoWrapCb = QtWidgets.QCheckBox(self.groupBox_2)
        self.autoWrapCb.setChecked(True)
        self.autoWrapCb.setObjectName("autoWrapCb")
        self.verticalLayout_3.addWidget(self.autoWrapCb)
        self.pauseReceiveCb = QtWidgets.QCheckBox(self.groupBox_2)
        self.pauseReceiveCb.setObjectName("pauseReceiveCb")
        self.verticalLayout_3.addWidget(self.pauseReceiveCb)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveRecvBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.saveRecvBtn.setObjectName("saveRecvBtn")
        self.horizontalLayout_3.addWidget(self.saveRecvBtn)
        self.clearRecvBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.clearRecvBtn.setObjectName("clearRecvBtn")
        self.horizontalLayout_3.addWidget(self.clearRecvBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.asciiSendRbtn = QtWidgets.QRadioButton(self.groupBox_3)
        self.asciiSendRbtn.setObjectName("asciiSendRbtn")
        self.horizontalLayout_4.addWidget(self.asciiSendRbtn)
        self.hexSendRbtn = QtWidgets.QRadioButton(self.groupBox_3)
        self.hexSendRbtn.setChecked(True)
        self.hexSendRbtn.setObjectName("hexSendRbtn")
        self.horizontalLayout_4.addWidget(self.hexSendRbtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.timeSendCb = QtWidgets.QCheckBox(self.groupBox_3)
        self.timeSendCb.setObjectName("timeSendCb")
        self.verticalLayout_5.addWidget(self.timeSendCb)
        self.timeEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.timeEdit.setInputMask("")
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_5.addWidget(self.timeEdit)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.recvText = QtWidgets.QTextEdit(self.groupBox_4)
        self.recvText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.recvText.setObjectName("recvText")
        self.verticalLayout_9.addWidget(self.recvText)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sendEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.sendEdit.setObjectName("sendEdit")
        self.horizontalLayout_5.addWidget(self.sendEdit)
        self.sendBtn = QtWidgets.QPushButton(self.groupBox_5)
        self.sendBtn.setObjectName("sendBtn")
        self.horizontalLayout_5.addWidget(self.sendBtn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.loadFileBtn = QtWidgets.QPushButton(self.groupBox_5)
        self.loadFileBtn.setObjectName("loadFileBtn")
        self.horizontalLayout_6.addWidget(self.loadFileBtn)
        self.loadFileEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.loadFileEdit.setObjectName("loadFileEdit")
        self.horizontalLayout_6.addWidget(self.loadFileEdit)
        self.sendFileBtn = QtWidgets.QPushButton(self.groupBox_5)
        self.sendFileBtn.setObjectName("sendFileBtn")
        self.horizontalLayout_6.addWidget(self.sendFileBtn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addWidget(self.groupBox_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 3)
        serialTool.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(serialTool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 23))
        self.menubar.setObjectName("menubar")
        serialTool.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(serialTool)
        self.statusbar.setObjectName("statusbar")
        serialTool.setStatusBar(self.statusbar)

        self.retranslateUi(serialTool)
        QtCore.QMetaObject.connectSlotsByName(serialTool)

    def retranslateUi(self, serialTool):
        _translate = QtCore.QCoreApplication.translate
        serialTool.setWindowTitle(_translate("serialTool", "串口调试工具"))
        self.groupBox.setTitle(_translate("serialTool", "串口参数"))
        self.serialBaudComb.setItemText(0, _translate("serialTool", "115200"))
        self.serialBaudComb.setItemText(1, _translate("serialTool", "9600"))
        self.serialBaudComb.setItemText(2, _translate("serialTool", "14400"))
        self.serialBaudComb.setItemText(3, _translate("serialTool", "38400"))
        self.serialBaudComb.setItemText(4, _translate("serialTool", "56000"))
        self.serialBaudComb.setItemText(5, _translate("serialTool", "57600"))
        self.serialBaudComb.setItemText(6, _translate("serialTool", "128000"))
        self.serialCheckComb.setItemText(0, _translate("serialTool", "None"))
        self.serialDataLenComb.setItemText(0, _translate("serialTool", "8"))
        self.serialDataLenComb.setItemText(1, _translate("serialTool", "5"))
        self.serialDataLenComb.setItemText(2, _translate("serialTool", "6"))
        self.serialDataLenComb.setItemText(3, _translate("serialTool", "7"))
        self.serialStopComb.setItemText(0, _translate("serialTool", "1"))
        self.serialStopComb.setItemText(1, _translate("serialTool", "2"))
        self.openBtn.setText(_translate("serialTool", "打开串口"))
        self.closeBtn.setText(_translate("serialTool", "关闭串口"))
        self.groupBox_2.setTitle(_translate("serialTool", "接收设置"))
        self.asciiRecvRbtn.setText(_translate("serialTool", "ASCII"))
        self.hexRecvRbtn.setText(_translate("serialTool", "HEX"))
        self.autoWrapCb.setText(_translate("serialTool", "自动换行"))
        self.pauseReceiveCb.setText(_translate("serialTool", "暂停接收"))
        self.saveRecvBtn.setText(_translate("serialTool", "保存数据"))
        self.clearRecvBtn.setText(_translate("serialTool", "清除显示"))
        self.groupBox_3.setTitle(_translate("serialTool", "发送设置"))
        self.asciiSendRbtn.setText(_translate("serialTool", "ASCII"))
        self.hexSendRbtn.setText(_translate("serialTool", "HEX"))
        self.timeSendCb.setText(_translate("serialTool", "定时发送（ms）"))
        self.timeEdit.setText(_translate("serialTool", "1000"))
        self.groupBox_4.setTitle(_translate("serialTool", "接收数据区"))
        self.groupBox_5.setTitle(_translate("serialTool", "发送数据区"))
        self.sendBtn.setText(_translate("serialTool", "发送"))
        self.loadFileBtn.setText(_translate("serialTool", "选择文件"))
        self.sendFileBtn.setText(_translate("serialTool", "发送文件"))

